# Generated by Django 5.0.2 on 2024-02-13 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_todolist_todo_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
