# Generated by Django 5.0.2 on 2024-02-13 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_delete_event'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoList',
            new_name='Event',
        ),
    ]
