# Generated by Django 5.0.2 on 2024-02-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_readingmaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='classList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('attributes', models.CharField(max_length=100)),
                ('completed', models.BooleanField(default=False)),
                ('time', models.TimeField()),
                ('date', models.CharField(max_length=100)),
            ],
        ),
    ]
