# Generated by Django 5.0.2 on 2024-02-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_classlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlist',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
