# Generated by Django 5.0.2 on 2024-02-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_classlist_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlist',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='classlist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classlist',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
