# Generated by Django 5.0.2 on 2024-02-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_classlist_date_alter_classlist_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlist',
            name='completed',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='classlist',
            name='current',
            field=models.BooleanField(),
        ),
    ]
