# Generated by Django 5.0.2 on 2024-02-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_classlist_completed_alter_classlist_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlist',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='classlist',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
