# Generated by Django 5.0.2 on 2024-02-16 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_classlist_completed_alter_classlist_current'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classlist',
            old_name='current',
            new_name='currently_taking',
        ),
    ]
