# Generated by Django 5.0.2 on 2024-03-05 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_remove_readingmaterial_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='classBadge',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='dormBadge',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='eventsBadge',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='facultyBadge',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hamBadge',
        ),
        migrations.AddField(
            model_name='profile',
            name='badges',
            field=models.BooleanField(default=False),
        ),
    ]
