# Generated by Django 5.0.2 on 2024-03-05 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_remove_profile_classbadge_remove_profile_dormbadge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='badges',
            field=models.JSONField(default=list),
        ),
    ]
