# Generated by Django 5.0.2 on 2024-03-05 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_alter_profile_badges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='badges',
        ),
        migrations.AddField(
            model_name='profile',
            name='classBadge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='dormBadge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='eventsBadge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='facultyBadge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='hamBadge',
            field=models.BooleanField(default=False),
        ),
    ]
