# Generated by Django 5.0.2 on 2024-03-05 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_remove_profile_badges_profile_classbadge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='badges',
            field=models.BooleanField(default=False),
        ),
    ]
