# Generated by Django 5.0.2 on 2024-03-10 01:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0018_post"),
        ("mainapp", "0024_profile_badgescore"),
    ]

    operations = []
