# Generated by Django 5.0.2 on 2024-03-09 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_event_user'),
        ('mainapp', '0026_merge_0018_post_0025_post'),
    ]

    operations = [
    ]
