# Generated by Django 5.0.2 on 2024-03-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0027_merge_0018_event_user_0026_merge_0018_post_0025_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="supplyMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("read", models.BooleanField(default=False)),
            ],
        ),
    ]
