# Generated by Django 5.0.2 on 2024-03-16 03:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0025_merge_0018_post_0024_profile_badgescore"),
        ("mainapp", "0027_merge_0018_event_user_0026_merge_0018_post_0025_post"),
    ]

    operations = []
