# Generated by Django 5.0.2 on 2024-03-16 04:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0028_merge_20240316_0300"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
    ]
