# Generated by Django 5.0.2 on 2024-03-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0031_alter_usersupply_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplyItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("purchased", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="usersupply",
            name="supply",
        ),
        migrations.AlterUniqueTogether(
            name="usersupply",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="usersupply",
            name="user",
        ),
        migrations.DeleteModel(
            name="Supply",
        ),
        migrations.DeleteModel(
            name="UserSupply",
        ),
    ]
