# Generated by Django 5.0.2 on 2024-03-12 20:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0025_merge_0018_post_0024_profile_badgescore"),
        ("mainapp", "0031_alter_usersupply_user"),
    ]

    operations = []
