# Generated by Django 5.0.2 on 2024-03-12 20:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0032_merge_20240312_2048"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="usersupply",
            unique_together=set(),
        ),
    ]
