# Generated by Django 5.0.2 on 2024-03-12 20:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0025_merge_0018_post_0024_profile_badgescore"),
        ("mainapp", "0032_supplyitem_remove_usersupply_supply_and_more"),
    ]

    operations = []
